In [132]:
import pandas as pd
import openpyxl
import os

In [133]:
Feedback = pd.read_excel(r'C:\Users\User\Documents\Py by Imamf\Reliability\Feed back Anomali Week05.xlsx',
                        sheet_name = 'Sangatta 2',
                         header = 3,
                         usecols = 'A:AG')

In [134]:
Feedback.drop(Feedback.columns[[1,7,10,11,12,13,14,15,16,17,18,20,22,23,24,25,26,27,28,29,30]],axis=1,inplace=True)

In [135]:
Feedback.head(10)

,Unit No.,OEM\nDescription,Meter\n(Start),Meter\n(End),Resp.\nGroup,Maintenance\nArea,Event End Time,Total\nEvent\nMaint.\nDuration,Status,Reported Fault/Job Description,Is Failure,GROUP
0,AC1255,ATL XAHS 250 DD,1234.0,1234.0,Workshop,Workshop Melawan,2022-01-14 19:40:00,1211.666667,Open,Engine hard to running,Yes,SUPPORT
1,CR3041,TAD GR700EX CRANE,3631.0,3631.0,Workshop,Workshop Melawan,2022-01-14 19:40:00,2244.666667,Open,Engine can't running,Yes,CRANE
2,DZ1551,CAT D10 T,58524.9,58524.9,Workshop,Workshop TWS,2022-01-16 03:00:00,168.000000,Open,"Schedule undercarriage replacement, planned 16...",No,CATERPILLAR D10R and T
3,DZ1551,CAT D10 T,58524.9,58524.9,Workshop,Workshop TWS,2022-01-16 03:00:00,168.000000,Open,Electrical Inspection,No,CATERPILLAR D10R and T
4,DZ1551,CAT D10 T,58524.9,58524.9,Workshop,Workshop TWS,2022-01-16 03:00:00,168.000000,Open,Schedule transmission replacement,No,CATERPILLAR D10R and T
5,DZ1598,CAT D8 R,1327.9,1327.9,Workshop,Workshop Melawan,2022-01-14 19:40:00,406.166667,Open,Over run : engine fail,No,CATERPILLAR D8R
6,DZ8098,KOM D85 ESS-2,8215.7,8215.7,Field,Field Shop Pit Melawan,2022-01-14 19:40:00,76.750000,Open,Lhs Track Loose and Lhs Idler Loose Loc Cermai...,Yes,KOMATSU D85ESS
7,DR6002,TER SKF11 DRILL,1117.3,1117.3,Workshop,Workshop Melawan,2022-01-14 19:40:00,458.666667,Open,"Compressor tank, RH hand rail and raise cylind...",No,DRILLING
8,DR6002,TER SKF11 DRILL,1.0,1.0,Workshop,Workshop Melawan,2022-01-14 19:40:00,458.666667,Open,Electrical inspection,No,DRILLING
9,EX3184,HIT EX3600 6,64829.0,64829.0,Field,Field Shop IGS,2022-01-14 19:40:00,314.333333,Open,Over run : Continue tumbler replacement,No,HITACHI EX3600

In [194]:
wb = openpyxl.load_workbook('Weekly Maintenance Performance SGT Week 05 - Anomali (1).xlsx')
sheet = wb['SGT P.Metrics']

data_rows = []
for row in sheet['A7':'G47']:
    data_cols = []
    for cell in row:
        data_cols.append(cell.value)
    data_rows.append(data_cols)

#drop and add first row to be index 
report = pd.DataFrame(data_rows)
report.drop([1,2],axis=1,inplace=True)
report.columns = report.iloc[0]

#first row to be dropped
report = report.drop(0).reset_index(drop=True)

In [195]:
report.head(47)

0  Mechanical Availability   Week 01   Week 02   Week 03   Week 04
0                 Cat 789C  0.985402  0.945517    0.9638  0.953195
1                 Cat 785C  0.912604   0.90553  0.922396  0.924657
2        Volvo A40 Intraco  0.979663         1  0.827922  0.982357
3         Volvo A40 Thiess  0.901042  0.749876  0.860926  0.946474
4                  Cat 740  0.951736  0.924479  0.936676  0.959909
5    Service Truck Cat 740  0.916791   0.99256  0.936475  0.777308
6                  Cat 745  0.861452  0.884518  0.908777  0.919982
7      Cat 777D Coal Truck  0.943426  0.936547  0.943136  0.955959
8      Cat 777E Coal Truck  0.936099  0.945057   0.94719  0.972622
9        Cat 777D OB Truck   0.97495  0.945437  0.945599  0.963001
10             Water Truck  0.853616  0.791446  0.840575  0.854795
11               Mud Truck   0.99504  0.985615  0.974647  0.972451
12              KOM D85ESS       0.9  0.843679  0.963589  0.894646
13         Komatsu D65P-12  0.685268  0.795387  0.985323  0.960813
14          Hitachi EX5500  0.762566   0.90625  0.754972  0.814834
15          Hitachi EX3600  0.910301  0.951761  0.754839  0.764799
16          Hitachi EX2600  0.988095  0.978175  0.687778  0.974206
17       Hitachi EX2500 OB  0.966353  0.947834  0.861619  0.980305
18     Hitachi EX2500 COAL         1  0.993056         1   0.99359
19          Hitachi EX1900  0.957837  0.988095  0.918155  0.970707
20           Liebherr R984  0.930494  0.926401  0.931213  0.926202
21           Liebherr R350  0.962798  0.891369  0.745646  0.808103
22           Hitachi ZX350  0.937538  0.894612  0.959361  0.885717
23           Hitachi ZX200  0.885913  0.699157         1   0.86382
24           Komatsu PC400         1         1         1         1
25           Komatsu PC300  0.770999   0.88459  0.787597  0.806146
26      Kom PC200 Long Arm  0.822371  0.534722  0.971133  0.900298
27   Kom PC200 Flat Bucket  0.785714   0.93254  0.877778  0.979688
28                 Cat 834  0.926587  0.958209  0.946476  0.942212
29              Cat D10R/T  0.891121  0.887822  0.867751  0.933281
30                 Cat D8R  0.809359  0.849962  0.877249  0.849166
31                 Cat 18M  0.926587       0.9  0.879206  0.944495
32                 Cat 16M  0.944382  0.892237   0.82884  0.900933
33                   Drill   0.94089  0.978423  0.996021  0.946669
34                   Pumps  0.923611  0.930328  0.886234  0.919919
35           TJ Rent Dozer  0.928158   0.86169  0.919516  0.863279
36                   Crane  0.827381  0.815476  0.841572  0.834588
37                  Loader  0.950184  0.967474  0.874438   0.84502
38                 Manhaul  0.562486  0.583932   0.57889  0.614399
39            Medium Truck  0.973669  0.968626  0.947864  0.973263

In [203]:
#set underperformed unit type to be in a dataframe
anomalies = report.loc[report['Week 04'] <= 0.9]
anomalies.reset_index(drop=True)

0  Mechanical Availability   Week 01   Week 02   Week 03   Week 04
0    Service Truck Cat 740  0.916791   0.99256  0.936475  0.777308
1              Water Truck  0.853616  0.791446  0.840575  0.854795
2               KOM D85ESS       0.9  0.843679  0.963589  0.894646
3           Hitachi EX5500  0.762566   0.90625  0.754972  0.814834
4           Hitachi EX3600  0.910301  0.951761  0.754839  0.764799
5            Liebherr R350  0.962798  0.891369  0.745646  0.808103
6            Hitachi ZX350  0.937538  0.894612  0.959361  0.885717
7            Hitachi ZX200  0.885913  0.699157         1   0.86382
8            Komatsu PC300  0.770999   0.88459  0.787597  0.806146
9                  Cat D8R  0.809359  0.849962  0.877249  0.849166
10           TJ Rent Dozer  0.928158   0.86169  0.919516  0.863279
11                   Crane  0.827381  0.815476  0.841572  0.834588
12                  Loader  0.950184  0.967474  0.874438   0.84502
13                 Manhaul  0.562486  0.583932   0.57889  0.614399

In [234]:
#summon the data for MA units
fleet_ma = pd.read_excel(r'C:\Users\User\Documents\Py by Imamf\Reliability\MA and PM Projection Weekly Planning WEEK 05 Plant VS Actual.xlsx',
                        sheet_name = 'MA-PM Projection Plan vs Act',
                         usecols = 'A:AA')
fleet_ma.drop(fleet_ma.columns[[2,3,4,9,12,13,14,19,20,21,22,23,24]],axis=1,inplace=True)
fleet_ma.dropna(inplace=True)

In [235]:
fleet_ma.head(20)

,Fleet,Jumlah Unit,Scheduled Hours\n(08) Planning,Scheduled Hours\n(08) Week 05 Actual,Unscheduled Hours\n(09),Unscheduled Hours\n(09) Week 04 Actual,Scheduled Opportune (018) Planning,Scheduled Opportune (018) Actual Week 04,MA Projection,MA Actual Week 04,PM Projection,PM Actual Week 04,Unnamed: 25
13,CATERPILLAR 785C,111.0,851.0,580.08336,900.0,1434.66670,0.0,7.33347,0.927553,0.913017,0.629904,0.357763,860.0
14,CATERPILLAR 789C,11.0,90.0,33.33332,220.0,175.83333,72.0,0.00000,0.913420,0.929410,0.698276,0.435210,141.0
16,MUD TRUCK,5.0,48.0,10.00000,20.0,62.00000,5.0,0.70000,0.919048,0.913000,0.726027,0.200000,42.0
17,WATER TRUCK,7.0,66.0,129.00000,40.0,143.90000,7.0,1.00000,0.909864,0.797000,0.646018,0.141000,132.0
18,CAT 777D OB TRUCK,22.0,60.0,7.80000,100.0,193.00000,60.0,1.20000,0.956710,0.969087,0.545455,0.453829,170.0
19,CAT 777D COAL TRUCK,25.0,264.0,60.30000,200.0,113.90000,24.0,1.20000,0.889524,0.963742,0.590164,0.419387,292.0
20,CAT 777E COAL TRUCK,17.0,108.0,5.90000,90.0,37.30000,17.0,0.50000,0.930672,0.951885,0.581395,0.701127,212.0
21,CATERPILLAR 740,20.0,214.0,41.90000,100.0,130.00000,20.0,0.50000,0.906548,0.963000,0.700599,0.222000,98.0
22,CATERPILLAR 745,16.0,168.0,66.80000,80.0,218.20000,16.0,3.20000,0.907738,0.894000,0.696970,0.486000,124.0
23,SERVICE TRUCK CAT 740,4.0,66.0,38.00000,20.0,2.30000,4.0,0.00000,0.872024,0.940000,0.777778,0.315000,96.0
24,VOLVO A40G,4.0,30.0,0.00000,20.0,53.00000,4.0,0.00000,0.925595,0.937000,0.629630,0.000000,24.0
38,CRANE,6.0,97.0,2.00000,10.0,192.00000,0.0,0.00000,0.893849,0.831597,0.906542,0.010309,0.0
40,MANHAUL,34.0,218.0,76.80000,150.0,2141.00000,0.0,0.00000,0.935574,0.619000,0.592391,0.074000,202.0
41,MEDIUM TRUCK,10.0,80.0,11.00000,45.0,9.70000,0.0,0.00000,0.925595,0.937000,0.640000,0.091000,44.0

In [296]:
#summon all fleet MER
fleet_MER = pd.read_excel(r'C:\Users\User\Documents\Py by Imamf\Reliability\MA and PM Projection Weekly Planning WEEK 05 Plant VS Actual.xlsx',
                        sheet_name = 'MER',
                         usecols = 'A:AH')
fleet_MER.drop(fleet_MER.columns[[0,1,3,4,5,6,7,8,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26]],axis=1,inplace=True)
fleet_MER.dropna(inplace=True)

In [297]:
fleet_MER.reset_index(drop=True,inplace=True)
fleet_MER.columns = fleet_MER.iloc[0]
fleet_MER.drop(0,inplace=True)
fleet_MER.head(30)

,Unit,PMD\n(08),UMD\n(09),Mech\nAvail\n%,Phys\nAvail\n%,Delay\nSMU\n%,Ann \nSMU\nHrs,Ann\nWork\nHrs,OPE\n%,PM\n%,GROUP
1,CP1780,0,0,1,1,0,2039.44,2039.44,0.00678886,1,COMPACTOR
2,CP1781,0,36.25,0.811198,0.811198,0,2151.98,2151.98,0,0,COMPACTOR
3,CR1563,2,0,0.989583,0.989583,0,1916.25,1916.25,0,1,CRANE
4,CR3039,0,0,1,1,0,2190,2190,0,0,CRANE
5,CR3000,0,0,1,1,0,4060.62,4060.62,0,0,CRANE
6,CR3004,0,0,1,1,0,958.125,958.125,0,0,CRANE
7,CR3041,0,192,0,0,0,0,0,0,0,CRANE
8,CR3044,0,0,1,1,0,501.875,501.875,0,0,CRANE
9,DZ1706,0,4.83333,0.974826,0.974826,0.000890033,5126.73,5122.16,0.0178016,0.216217,CATERPILLAR 834
10,DZ1707,0,0,1,1,0,4902.4,4902.4,0.0591365,1,CATERPILLAR 834
11,DZ8107,0,3.33333,0.982639,0.982639,0.0164905,3596.77,3537.45,0.0359928,0.545455,CATERPILLAR 834
12,DZ8108,0,10.6667,0.944444,0.944444,0,3789.91,3789.91,0.0305291,0.219512,CATERPILLAR 834
13,DZ3005,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
14,DZ3031,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
15,DZ3035,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
16,DZ3047,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
17,DZ3049,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
18,DZ1551,126.833,0,0.33941,0.33941,0,1888.88,1888.88,0,1,CATERPILLAR D10R and T
19,DZ1561,0,0,1,1,0.000714187,6389.02,6384.45,0.0192061,1,CATERPILLAR D10R and T
20,DZ1563,0,10.75,0.94401,0.94401,0,5868.89,5868.89,0.0190053,0.0851064,CATERPILLAR D10R and T
21,DZ1565,0,0,1,1,0,6388.26,6388.26,0.0192369,1,CATERPILLAR D10R and T
22,DZ1568,2.16667,8.5,0.944444,0.944444,0,6236.94,6236.94,0.0448095,0.328948,CATERPILLAR D10R and T
23,DZ1636,0,0,1,1,0,6631.59,6631.59,0,0,CATERPILLAR D10R and T
24,DZ1637,0,0,1,1,0,0,0,0,0,CATERPILLAR D10R and T
25,DZ1638,0,25.75,0.865885,0.865885,0,4799.75,4799.75,0,0,CATERPILLAR D10R and T
26,DZ1639,25,11.8333,0.80816,0.80816,0,4256.81,4256.81,0.0161638,0.687225,CATERPILLAR D10R and T
27,DZ1641,0,0,1,1,0.00300451,6074.2,6055.95,0,0,CATERPILLAR D10R and T
28,DZ3176,0,7.08333,0.963108,0.963108,0.00662806,6309.93,6268.11,0.0210378,0.123711,CATERPILLAR D10R and T
29,DZ3177,0,0,1,1,0.00148221,6156.33,6147.2,0.00436553,1,CATERPILLAR D10R and T
30,DZ3185,7.75,8.50001,0.915365,0.915365,0.00847338,5384.51,5338.89,0.0170261,0.507246,CATERPILLAR D10R and T